// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHSales.Models.Models;

public partial class VwDate
{
    public int? DateKey { get; set; }

    public DateOnly? FullDate { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

}